name: TEclass2
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.10
  - biopython
  - matplotlib
  - numpy<2.0
  - pandas<2.0
  - PyYAML
  - scikit-learn
  - scipy
  - tqdm
  - tensorboardX
  - openssl
  - yaml
  - pip:
    - torch<1.13
    - tokenizers
    - torchvision
    - transformers==4.17
    - accelerate

